### ISSUE TITLE
Bumbag Native – Feature Roadmap

### ISSUE THREAD

**Issue by jxom** [bumbag/bumbag-ui#118]
Bumbag v2 has now been released with support for React Native (Bumbag Native)! At the moment, Bumbag Native only supports a small range of primitive components, however it will be nice if we could extend the support to more high-level components.

### Foundation

- [x] **`Provider`**

### Primitives

- [x] **`Box`**
- [x] **`Box.Safe`**
- [x] **`Box.Scroll`**
- [x] **`Box.KeyboardAvoiding`**
- [x] **`Flex`** ([from Bumbag](https://bumbag.style/the-box-primitive/flex/))

### Typography

- [x] **`Heading`** ([from Bumbag](https://bumbag.style/typography/heading/))
- [ ] `Link` ([from Bumbag](https://bumbag.style/typography/link/))
- [ ] `List` ([from Bumbag](https://bumbag.style/typography/list/))
- [x] **`Text`** ([from Bumbag](https://bumbag.style/typography/text/))

### Layout

- [ ] `FieldStack` ([from Bumbag](https://bumbag.style/form/field-stack/)
- [x]  **`Hide`** ([from Bumbag](https://bumbag.style/layout/hide/)
- [x] **`Group`** ([from Bumbag](https://bumbag.style/layout/group/)
- [x] **`Level`** ([from Bumbag](https://bumbag.style/layout/level/)
- [x] **`Set`** ([from Bumbag](https://bumbag.style/layout/set/)
- [x]  **`Show`** ([from Bumbag](https://bumbag.style/layout/show/)
- [x] **`Stack`** ([from Bumbag](https://bumbag.style/layout/stack/)

### Components

- [ ] `ActionButtons` ([from Bumbag](https://bumbag.style/components/action-buttons/))
- [ ] `Alert` ([from Bumbag](https://bumbag.style/components/alert/))
- [ ] `Avatar` ([from Bumbag](https://bumbag.style/components/avatar/))
- [ ] `Badge` ([from Bumbag](https://bumbag.style/components/badge/))
- [ ] `BottomSheet` ([inspiration](https://gorhom.github.io/react-native-bottom-sheet/))
- [x] **`Button`** ([from Bumbag](https://bumbag.style/components/button/))
- [ ] `Card` ([from Bumbag](https://bumbag.style/components/card/))
- [ ] `Dialog` ([inspired by React Native Paper's Dialog](https://callstack.github.io/react-native-paper/dialog.html))
- [ ] `Dialog.Alert` ([inspo](https://backpack.github.io/components/alert?platform=native))
- [ ] `Divider` ([from Bumbag](https://bumbag.style/components/divider/))
- [ ] `DropdownMenu` ([from Bumbag](https://bumbag.style/components/dropdown-menu/) | [inspired by React Native Paper's Menu](https://callstack.github.io/react-native-paper/menu.html))
- [ ] `Fab` ([inspired by React Native Paper's Fab](https://callstack.github.io/react-native-paper/fab.html))
- [x] **`Icon`** ([from Bumbag](https://bumbag.style/components/icon/))
- [x] `List.Flat`
- [x] `List.Sectioned`
- [x] `List.Virtualized`
- [x] **`Image`**
- [ ] `Image.Background`
- [ ] `Menu` ([from Bumbag](https://bumbag.style/components/menu/) | like `Row`)
- [ ] `BottomNav` ([inspired by React Native Paper's BottomNavigation](https://callstack.github.io/react-native-paper/bottom-navigation.html))
- [ ] `TopNav` ([inspired by React Native Paper's Header](https://callstack.github.io/react-native-paper/appbar-header.html))
- [ ] `Popover` ([from Bumbag](https://bumbag.style/components/popover/))
- [ ] `Picker` ([inspired by Backpack's Picker](https://backpack.github.io/components/picker?platform=native))
- [ ] `ProgressBar` ([from Bumbag](https://bumbag.style/components/progress-bar/))
- [ ] `Rating` ([from Bumbag](https://bumbag.style/components/rating/))
- [ ] `SearchBar` ([inspiration](https://callstack.github.io/react-native-paper/searchbar.html))
- [x] **`Spinner`** ([from Bumbag](https://bumbag.style/components/spinner/))
- [ ] `Tabs` ([from Bumbag](https://bumbag.style/components/tabs/))
- [ ] `Tag` ([from Bumbag](https://bumbag.style/components/tag/))
- [ ] `Toast` ([inspo](https://magnus-ui.com/docs/snackbar/))
- [ ] `Tooltip` ([from Bumbag](https://bumbag.style/components/tooltip/))

### Form

- [ ] `Autosuggest`/`AutosuggestField` ([like this](https://www.npmjs.com/package/react-native-autocomplete-input))
- [x] **`Checkbox`/`CheckboxField`** ([from Bumbag](https://bumbag.style/form/checkbox/))
- [x] **`CheckboxGroup`/`CheckboxGroupField`**
- [ ] `FieldStack` ([from Bumbag](https://bumbag.style/form/field-stack/))
- [x] **`FieldWrapper`** ([from Bumbag](https://bumbag.style/form/field-wrapper/))
- [x] **`Input`/`InputField`** ([from Bumbag](https://bumbag.style/form/input/))
- [x] **`Radio`** ([from Bumbag](https://bumbag.style/form/radio/))
- [x] **`RadioGroup`/`RadioGroupField`**
- [ ] `Select`/`SelectField` ([from Bumbag](https://bumbag.style/form/select/))
- [x] **`Switch`/`SwitchField`** ([from Bumbag](https://bumbag.style/form/switch/))
- [x] **`SwitchGroup`/`SwitchGroupField`** ([from Bumbag](https://bumbag.style/form/switch-group/))
- [ ] **`Textarea`/`TextareaField`** ([from Bumbag](https://bumbag.style/form/textarea/))

### Utilities

- [ ] `Drawer` ([from Bumbag](https://bumbag.style/utilities/drawer/) | [inspo](https://callstack.github.io/react-native-paper/drawer-section.html))
- [ ] `Hidden` ([from Bumbag](https://bumbag.style/utilities/hidden/))
- [x] **`List`**
- [ ] `Modal` ([from Bumbag](https://bumbag.style/utilities/modal/))
- [ ] `Overlay` ([from Bumbag](https://bumbag.style/utilities/overlay/))
- [ ] `Portal` ([from Bumbag](https://bumbag.style/utilities/portal/))
- [x] **`Pressable`**
- [ ] **`RefreshControl`**
- [ ] **`StatusBar`**
- [x] **`Touchable`**
- [x] **`Touchable.Highlight`**
- [x] **`Touchable.Opacity`**

**Comment by iamclaytonray** [comment]
In the vast majority of apps, `Drawer` would be created from React Navigation. IMO, it should be designed with that in mind.
